### ISSUE TITLE
Keep original field value when editing existing objects in Admin

### ISSUE THREAD

**Issue by malexeev** [deschler/django-modeltranslation#238]
I think this might be related to #128.

At the moment  original field value seems to be automatically replaced by the value from the current 
request language when editing objects via admin.

Sometimes it may become a real problem. 
For example - removing django-modeltranslation from the application - all original fields are essentially corrupted and not the same anymore.
Or in legacy systems - original field value may be utilized by some external app.

It would be nice to have some simple way to preserve original fields values (in Admin at least).

Maybe a settings variable - "MODELTRANSLATION_KEEP_ORIGINAL"
If set to True then editing existing objects in Admin would not change the original value.
If False, or when adding new - work as-now.

**Comment by rubenanapu** [comment]
In my case, instead of having `name` and `name_en`, I just removed `en` from _**MODELTRANSLATION_LANGUAGES**_

The problem is that when there is no translation for the active language (let's say, `es / Spanish`), the _**instance.name**_ would return an empty string, instead of what we have at the _**name**_ column. To return the value of **_name_** instead of an empty value, what I did was the following:

Just modified the last line of [`TranslationFieldDescriptor.__get__`](https://github.com/deschler/django-modeltranslation/blob/master/modeltranslation/fields.py#L412) to the following

```diff
-           return default
+           return default or instance.__dict__[self.field.name]
```

In my tests, it seems to be working as I expected.
