### ISSUE TITLE
modeltranslation doesn't migrate flatpages in Django 1.7

### ISSUE THREAD

**Issue by thomwiggers** [deschler/django-modeltranslation#255]
With Django 1.7s switch to migrations, modeltranslation no longer adds the required fields to the table `django_flatpages` when you do `./manage.py syncdb`. When you do `sync_translation_fields`, the fields are added.

This however does mean that unittests fail because `./manage.py test` only runs `syncdb`/`migrate`, and not `sync_translation_fields`.

**Comment by dadoeyad** [comment]
I have a related issue. As you said the migrations are created in "django/contrib/flatpages/migrations" 
That's okay for local machine, but I'm using Heroku and I can't change anything created by `pip install` 

Even doing `heroku run ./manage.py makemigrations flatpages` says that it created the migration but nothing happens when I apply. I'm guessing that's because Heroku deletes it.
The only thing I can think of right now is copying the whole django folder to my project, but that's really bad.
Any idea on how else I can do this?

**Comment by thomwiggers** [comment]
You might be able to solve that issue by using the `MIGRATION_MODULES`
configuration option of Django. We are now using something like this:

    MIGRATION_MODULES = {
        'flatpages': 'ourapp.fixtures.flatpages_migrations',
        'sites': 'cachegame.fixtures.sites_migations',
    }

**Comment by dadoeyad** [comment]
@thomwiggers That's a great idea actually. At the end I made a fake migration in another app and put the SQL commands inside it.
But your idea is better. Thanks!
