### ISSUE TITLE
Using blocktrans in templates

### ISSUE THREAD

**Issue by nathandh8** [deschler/django-modeltranslation#296]
Variables within a {% blocktrans %} template tag don't seem to render correctly.

    <h1>Books in category {{category.title}}:</h1>

Returns the correct title value for any given language.

    {% blocktrans %}<h1>Books in category {{category.title}}:</h1>{% endblocktrans %}

Returns None: 'Books in category :'

Any workaround?

**Comment by deschler** [comment]
Here is a workaround:
   
    {% blocktrans with title=category.title %}<h1>Books in category {{ title }}:</h1>{% endblocktrans %}

**Comment by nathandh8** [comment]
Thanks for the tip!

**Comment by cormier** [comment]
Oh, sorry, I didn't mean to pollute this issue by adding unnecessary references -- I only wanted to refer to it in my commit for my own documentation.

I see that this issue is closed: is there a legitimate reason for this behaviour, or is it an issue that we should fix? Inserting all the variables in the blocktrans seems counterintuitive to me.
