### ISSUE TITLE
modeltranslations break ORM datetimes()

### ISSUE THREAD

**Issue by slav0nic** [deschler/django-modeltranslation#324]
From https://github.com/stephenmcd/mezzanine/issues/1359

```python
In [24]: BlogPost.objects.filter(**{ 'publish_date__year':2015, 'publish_date__month':7}).datetimes('publish_date','day')
Out[24]: [(datetime.datetime(2015, 7, 21, 0, 0, tzinfo=<UTC>), datetime.datetime(2015, 7, 21, 0, 0, tzinfo=<UTC>))]

In [25]: BlogPost.objects.count()
Out[25]: 1

In [26]: BlogPost.objects.first().publish_date
Out[26]: datetime.datetime(2015, 7, 21, 22, 28, 8, tzinfo=<UTC>)
```

**Comment by zlorf** [comment]
Is ``BlogPost.objects.filter(**{ 'publish_date__year':2015, 'publish_date__month':7}).count() == 1``?

**Comment by slav0nic** [comment]
yes
```
In [4]: BlogPost.objects.filter(**{ 'publish_date__year':2015, 'publish_date__month':7}).count()
Out[4]: 1

In [5]: BlogPost.objects.filter(**{ 'publish_date__year':2015, 'publish_date__month':7}).datetimes('publish_date','day')
Out[5]: [(datetime.datetime(2015, 7, 21, 0, 0, tzinfo=<UTC>), datetime.datetime(2015, 7, 21, 0, 0, tzinfo=<UTC>))]
```
it's fail only on django 1.8.3, in 1.7- work correct

**Comment by henri-hulski** [comment]
The same with Python 2.7.9

**Comment by harzo** [comment]
Temporary bypass:
comment line
{% block date_hierarchy %}{% date_hierarchy cl %}{% endblock %}
like this

in
XXX/site-packages/grappelli_safe/templates/admin/change_list.html

Now you are able to add new posts.

**Comment by vstoykov** [comment]
With django 1.8 `datetimes()` also no't work and raise an exception in the administration:

    'tuple' object has no attribute 'year'

The problem is caused by `FallbackValuesListQuerySet.iterator()` method https://github.com/deschler/django-modeltranslation/blob/master/modeltranslation/manager.py#L452

It add `self.annotation_names` to `fields` but if both are the same you now have tuple with two field names which are the same. Also `self.flat` is `True` which means that we have only one field but because `len(fields)` is now `2` this check fails https://github.com/deschler/django-modeltranslation/blob/master/modeltranslation/manager.py#L456 and it yields tuple instead of single item.

Probably adding field names from `annotated_fields` need to happens only if they are not present already in `fields`

**Comment by steckerhalter** [comment]
what's currently the "solution" for this to be able to use model translations with Mezzanine? to downgrade Django to v1.7?

**Comment by deschler** [comment]
@vstoykov Can you create a pull request with the suggested fix? I'd be glad to issue a bugfix release if it solves the problem.

**Comment by vstoykov** [comment]
I will create one

**Comment by vstoykov** [comment]
I submitted by PR #331

**Comment by vstoykov** [comment]
And fixed my tests for Django 1.4 and 1.5.

@steckerhalter can you see if with changes in my pull request everything works for you?

**Comment by steckerhalter** [comment]
@vstoykov ok, I will check

**Comment by steckerhalter** [comment]
@vstoykov it works for me... tested it with my project, cheers

**Comment by vstoykov** [comment]
@deschler Can you look at my PR and if you are happy with it you can merge it

**Comment by deschler** [comment]
Patch looks good, merged it into master. Thanks alot for your help!
