### ISSUE TITLE
ImportError: cannot import name 'checksum'

### ISSUE THREAD

**Issue by JuniorBee** [deschler/django-modeltranslation#464]

**Comment by icelic** [comment]
I resolved it by deleting modeltranslation folder in env/lib/site-packages and reinstalling django-modelstranslation. 

If it still doesn't work try to do the same steps again but with this version https://github.com/deschler/django-modeltranslation/issues/436#issuecomment-370761348

**Comment by RahbarqulovAzizbek** [comment]
thanks a lotttt

**Comment by salahsaeed19** [comment]
**Documenting the Solution for ImportError Issue in modeltranslation Library Due to Missing Gettext Files**

### The Problem:
While running a Django project that uses the `modeltranslation` library, the following error occurred:

```python
ImportError: cannot import name 'checksum' from 'modeltranslation.models'
```

### The Cause:
The issue was caused by the absence of the **gettext** library, which is required by the project or dependencies like `modeltranslation` to handle translations.

### The Solution:
To resolve this issue, follow these steps:

1. **Download Gettext Files:**
   - Download the required files from the following link:
     [[gettext for Windows](https://mlocati.github.io/articles/gettext-iconv-windows.html)](https://mlocati.github.io/articles/gettext-iconv-windows.html)
   - Download the following files:
     - **shared1**
     - **static2**

2. **Install the Files:**
   - After downloading, install the files on your system in the default location or a custom directory of your choice.

3. **Add the Path to Environment Variables:**
   - Search for "edit the system environment variables" in the Start Menu and select it.
   - In the **System Variables** section:
     - Select the `Path` variable and click "Edit."
     - Add the following paths to the list:
       ```plaintext
       C:\Program Files\gettext-iconv\bin
       C:\gettext\bin
       ```
     - If you installed the files in a custom directory, ensure the path matches your installation location.

4. **Restart the System:**
   - To apply the changes and activate the environment variables, restart your computer.

5. **Run the Project:**
   - After restarting the system, open your Django project again and run it. The project should now work without any errors.

### Notes:
- Ensure the installed files match your operating system architecture (32-bit or 64-bit).
- If you are working on a project that will be transferred to other machines, include these steps as part of the environment setup documentation.

### The Result:
After performing the above steps, the issue was successfully resolved, and the project ran without errors.
