### ISSUE TITLE
When migrate with translation, delete already registered data

### ISSUE THREAD

**Issue by luchiago** [deschler/django-modeltranslation#586]
I don't know if it's a bug or default behavior of the project, but when I tried to use this package in my project on a model, it deleted all previous data of the fields from the model.

Python: 3.7.3
Django: 2.2.4
Database: PostgreSQL 10.4

**Comment by christianwgd** [comment]
Hi, i'm pretty sure that django-modeltranslation didn't delete any data in your database. What it does is creating new fields in your database that have a language prefix. If you have for example a "name" attribute in a model there is now an additional "name_en" and same for other languages. If you now use your django app to view the data it will be empty because the new fields are used. See the appended screenshot.
<img width="216" alt="translated_db" src="https://user-images.githubusercontent.com/9281647/109643577-b3445000-7b54-11eb-9614-9e4aa5d9fa0c.png">

Can you have a look in your database by using e.g. pgadmin? You will see, the old fields are still there, but not used in the app.

**Comment by luchiago** [comment]
Hmm, now I got it. I saw in Postgres how it's working. But how can I show the field in admin after migration? It's empty on admin but it does have data in Postgres.
![image](https://user-images.githubusercontent.com/30028621/109645156-36ee4480-7b35-11eb-809c-4aeec0620098.png)
![image](https://user-images.githubusercontent.com/30028621/109645191-41a8d980-7b35-11eb-8138-c3bc4c440b74.png)

**Comment by christianwgd** [comment]
Ok, I didn't have the problem, since i started with translated models. But may be the manage.py "dumpdata" and "loaddata" commands will help you. 
See the docs:
https://django-modeltranslation.readthedocs.io/en/latest/installation.html?highlight=loaddata#modeltranslation-loaddata-retain-locale
and:
https://django-modeltranslation.readthedocs.io/en/latest/commands.html?highlight=loaddata#the-loaddata-command

If all fails, you can write a tiny script which copies your field values to the translated ones.

**Comment by luchiago** [comment]
Okay, I'll do it. Thanks!

**Comment by Simouche** [comment]
this happened to me too.
you should run `python manage.py update_translation_fields`.
